# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "announcement-bar-app"
client_id = "8f73f37f83d4e4bcc81d2086751572bd"
application_url = "https://genesis-beings-cards-typical.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://genesis-beings-cards-typical.trycloudflare.com/auth/callback",
  "https://genesis-beings-cards-typical.trycloudflare.com/auth/shopify/callback",
  "https://genesis-beings-cards-typical.trycloudflare.com/api/auth/callback",
  "https://genesis-beings-cards-typical.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "theme-dev-store-macksik.myshopify.com"
